# カスタムアクションの作り方[公式] -> https://docs.github.com/ja/actions/creating-actions/about-custom-actions

# name: マーケットプレイスに出した時のタイトル名に該当する。
name: "Get & Cache Dependencies"
# description: マーケットプレイスに出した時の、タイトルの下の説明文に該当する。
description: "Get the dependencies (via npm) add cache them."
# composite actionを作る際は必ず「runs」を入れる。
runs:
  # composite actionを作る際は必ず「using: 'composite'」を入れる。
  using: "composite"
  # stepsの中身は、ワークフローの記載と同じで使える。
  steps:
    - name: cached Deps2
      run: echo cached Deps2
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      # runキーを使う場合は、shellキーの記載が必須になる。※ usesキーの場合は記載する必要がない。
      shell: bash
